/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4.3-5-g3f28c576e0-20230404"
#endif /* AVUTIL_FFVERSION_H */
